### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zunichky/authenication#1]
A couple issues I'm seeing:

- I'm still seeing a link to create a New Team, even when I'm not signed in
- When I *am* signed in, I don't see links to Edit or Destroy teams on the `index` action and I also don't see a link to Edit on the `show` action

**Comment by zunichky** [comment]
All fixed. I made the edit/destroy only work for teams that you create. The other teams are pulled from nhl.com, so if you delete/edit the stats it would just re-pull the information up about the team.

**Comment by chrisvfritz** [comment]
:+1: Looks good! :tada:
